### PR TITLE
Add pan parameter to reverb effect

### PR DESCRIPTION
**Pull request by f-f**
Right now the reverb is always perfectly stereo even if the source is panned, so this PR adds the possibility of panning the reverb too

EDIT: I'm not sure if I opened the PR against the correct branch?

### CODE REVIEW

**Review by telephon — CHANGES_REQUESTED** [review]
The variable `snd` holds a signal of arbitrary size (we know the size, it has `numChannels`). Your implementation will work for stereo only.

Also there is a whitespace indentation problem, maybe you need to check (tabs not spaces).

**Comment by telephon** [comment]
Here is roughly how you could do it, but it's not yet right for the stereo case.

```supercollider
(
{
	var reverbPan = 0.5;
	var in = (0..7);
	var sig = SinOsc.ar(2 ** in * 100);
	var offset = reverbPan * in.size;
	var all = PanAz.ar(in.size, sig, (0..7) + offset * 2 / in.size, width: 1, orientation: 0);
	all.sum
}.plot
)
```

**Comment by telephon** [comment]
@f-f do you want to work further on it?

**Comment by f-f** [comment]
@telephon sorry I went on to other things and did not manage to work further on this. I'll close it

**Pull request closed without merging**
