### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fracnesco**
Fix typo in adding global effects hack

### CODE REVIEW

**Comment by telephon** [comment]
thank you!

**Comment by ndr-brt** [comment]
wait... what was the typo? I see only a different code formatting.
If the goal was to improve readability, I would have extracted the effect to a variable before adding it to the global effects

**Comment by fracnesco** [comment]
@ndr-brt missing semicolon on line 31

**Comment by ndr-brt** [comment]
yeah, missed that sorry :smiling_face_with_tear:

**Pull request merged**
