### PR TITLE
rms analysis support

### PR DESCRIPTION
**Pull request by telephon**
This branch adds rms analysis, it sends data to all registered clients of the server. The format is:

`["/rms", synthID, orbitIndex, peak1, power1, peak2, power2,  …]` (continuing for all audio channels).

The sending can be activated by sending the parameters:

`# rmsPeakLag "3" # rmsReplyRate "8"`  from tidal (you need to add those to tidal).

### CODE REVIEW

**Comment by telephon** [comment]
see: #74

**Comment by yaxu** [comment]
Thanks @telephon,
Pardon my ignorance, but how would the editor become a registered client of the server? Would doing this mean getting other OSC messages intended for sclang?

Presumably there's no issue with 'hand crafting' an OSC message to set the `rmsPeakLag` and `rmsReplyRate`, rather than going via Tidal?

**Comment by fdragovic** [comment]
thanks! trying to learn how the effects chains are handled and this and the
global effects pr are really helping :D

On Feb 14, 2018 3:56 PM, "Julian Rohrhuber" <notifications@github.com>
wrote:

see: #74 <https://github.com/musikinformatik/SuperDirt/issues/74>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/musikinformatik/SuperDirt/pull/76#issuecomment-365632196>,
or mute the thread

**Comment by fdragovic** [comment]
@yaxu it should already be sending osc just to 57110. if you filter out the
messages on that port instead of 6010 you can get the ones it sends to
sclang directly i think (:

**Comment by yaxu** [comment]
Sorry @fdragovic not sure exactly what you mean.. Ideally I just want the rms messages, going to port 6010.

**Comment by telephon** [comment]
you just send an OSC message `"/notify"` to scsynth, that is, normally to port `57110`.

**Comment by telephon** [comment]
sorry, I didn't mention this. I was a bit lazy and just followed the standard scheme for supercollider here.

If it helps, we can also route the messages through sclang and send exactly where you want to have it.

But maybe it is also easy like this. The editor must know the server port of course, which might be a disadvantage.

This is a general way to send information from the server to tidal or any other application.

**Comment by yaxu** [comment]
How do you tell scsynth which port to notify? Maybe routing via sclang is indeed best..

**Comment by telephon** [comment]
scsynth will know automatically from the message you send (there is a reply address in each)

**Comment by yaxu** [comment]
How? As I understand it, the outbound port won't be the same port as the one that is being listened to.

**Comment by yaxu** [comment]
Ah, I found this issue. https://github.com/supercollider/supercollider/issues/801
I've actually never seen a UDP client listening on the same port that they send from before. I'll look into doing this with Haskell.

**Comment by telephon** [comment]
Ah yes, of course. I can add a rerouting via sclang if Haskell doesn't work.

**Comment by telephon** [comment]
(doesn't send yet)

**Comment by yaxu** [comment]
One more feature request for this - it would be nice to have the option to have left/right channels analysed separately, for stereo VU metering.

**Comment by telephon** [comment]
This already happens (you get each of the channels separately, independent of the number of channels).

**Comment by telephon** [comment]
ok, sends now. just call:

`~dirt.startSendRMS`

**Comment by telephon** [comment]
again, the format is:

`["/rms", synthID, orbitIndex, peak1, power1, peak2, power2, …]` and so on for as many channels as you have specified.

**Comment by telephon** [comment]
maybe the OSC command should be `/tidal_rms`.

**Comment by yaxu** [comment]
I'm working on a minimal example of subscribing to scserver. Here's what I have so far, basically sending `/notify 1` - I see the `1` is needed from this: http://doc.sccode.org/Reference/Server-Command-Reference.html#/notify
```
import Sound.OSC.FD
import qualified Network.Socket as N
main = do udp <- udpServer "127.0.0.1" 0
          remote_addr <- N.inet_addr "127.0.0.1"
          let remote_sockaddr = N.SockAddrInet 57110 remote_addr
          sendTo udp (Message "/notify" [int32 1]) remote_sockaddr
          loop udp
  where loop udp = do m <- recvMessage udp
                      putStrLn $ show m
                      loop udp
```
But I get back `/fail "too many users"`

Quite a general issue but any clues appreciated!

**Comment by telephon** [comment]
Can you try and start the server with more logins?
```
s.options.maxLogins = 8;
s.reboot;
```

**Comment by yaxu** [comment]
@telephon Thanks, increasing the number of logins has indeed allowed more logins! :)

**Comment by yaxu** [comment]
Ok I can see numbers now!
I have six orbits going to a single stereo output, i.e. `[0, 0, 0, 0, 0, 0]`

I put `~dirt.startSendRMS` at the end of my startup, and get this error repeated 11 times:
`ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 2 server: localhost`

However it seems to work anyway. I get one osc message per orbit, each with four float values, as you describe, and they look good.

To be honest I'm not clear on what the difference/relationship between `rms` and `peak` are, but will play around with them.. Classic dirt is only calculating rms so far.

Thanks a lot for your help with this.

**Comment by telephon** [comment]
>I put `~dirt.startSendRMS` at the end of my startup, and get this error repeated 11 times:
`ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 2 server: localhost`

you may have to increase the 
`s.options.numAudioBusChannels = 1024 * 8`

But it shouldn't really happen (we don't use many busses). Maybe we you have an old version of one of the components (scynth /sclang).

>To be honest I'm not clear on what the difference/relationship between rms and peak are, but will play around with them.. Classic dirt is only calculating rms so far.

In the usual level indicators, you get a peak level of the signal as well, so that you can see if it has clipped. There is an example in `tests/testing-rms.scd`.

**Comment by yaxu** [comment]
Increasing audiobuschannels seems to have fixed it, thanks. I'm on SC v3.8.1

This is working fine now, perhaps ready to be merged? The only thing is I found the default 8Hz too slow and upped to 15Hz. I suggest a default of at least 10.

Here's a quick demo:
  https://www.youtube.com/watch?v=l1MNP2MWGTI

(that's captured at 20Hz with rms at 15Hz, so Nyquist is among us..)

**Comment by telephon** [comment]
> I'm on SC v3.8.1

That is too old now! https://github.com/supercollider/supercollider/releases

>The only thing is I found the default 8Hz too slow and upped to 15Hz. I suggest a default of at least 10.

The  defaults for the UGen are `replyRate = 20.0, peakLag = 3`. Should we use those?

**Pull request merged**
