### PR TITLE
Add three new default synths: pm, fmgrain and whistle

### PR DESCRIPTION
**Pull request by madskjeldgaard**
A suggestion to add three new default synths for added madness into the mix: 

pm: A Phase Modulation Synth 
fmgrain: A frequency modulated granular synth
whistle: A machine listening synth that extracts pitch information from your voice and uses it to control a fat, three oscillator bass synth.

### CODE REVIEW

**Comment by telephon** [comment]
@datamads feel free to let me know if you need support for this

**Comment by madskjeldgaard** [comment]
Oh fuck only just seen these messages now. So sorry telephon. I'll have a look at the code and update it!

**Comment by telephon** [comment]
no Problem !

**Comment by telephon** [comment]
(ping)

**Comment by telephon** [comment]
feel free to reopen!

**Comment by madskjeldgaard** [comment]
Oh man I totally forgot about this. So sorry!

**Comment by telephon** [comment]
No problem at all! I'm just cleaning up a bit. Just reopen if you continue …

**Pull request closed without merging**
